/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VooFrame.java
 *
 * Created on 30/11/2009, 00:58:23
 */

package view_projetofinallabbd;

import java.sql.*;
import javax.swing.*;
import java.util.*;
import model_projetofinallabbd.*;
import controler_projetofinallabbd.*;
import javax.swing.table.DefaultTableModel;

public class VooFrame extends javax.swing.JFrame {
    /** Creates new form VooFrame */
    public VooFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.trechos_tmp = new Vector<Trecho>();
        this.atualizaVoos();
    }
    private int index = 0;
    private int index_trecho = 0;
    private boolean estado = true;
    private boolean estado_trecho = true;
    private Vector<Voo> voos = new Vector<Voo>();
    private Vector<Aeroporto> aeroportos = new Vector<Aeroporto>();

    private Vector<Trecho> trechos_tmp;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        vPrim = new javax.swing.JButton();
        vProx = new javax.swing.JButton();
        vUlt = new javax.swing.JButton();
        vAnt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vEdit = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        vInserir = new javax.swing.JToggleButton();
        vCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tPrimeiro = new javax.swing.JButton();
        tAnt = new javax.swing.JButton();
        tProx = new javax.swing.JButton();
        tUlt = new javax.swing.JButton();
        tEdit = new javax.swing.JToggleButton();
        tInserir = new javax.swing.JToggleButton();
        tCancelar = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setTitle("Voos");

        jLabel1.setText("Voos");

        fechar.setActionCommand("Fechar");
        fechar.setLabel("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo do Voo");

        jLabel4.setText("Dia da semana");

        jLabel5.setText("Comp Aérea");

        jLabel6.setText("Trechos");

        jLabel16.setText("Mostrando voo");

        jLabel17.setText("i");

        jLabel18.setText("de");

        jLabel19.setText("N");

        vPrim.setText("Primeiro voo");
        vPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPrimActionPerformed(evt);
            }
        });

        vProx.setText("Próximo voo");
        vProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vProxActionPerformed(evt);
            }
        });

        vUlt.setText("Ultimo voo");
        vUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vUltActionPerformed(evt);
            }
        });

        vAnt.setText("Voo Anterior");
        vAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vAntActionPerformed(evt);
            }
        });

        jLabel10.setText("Primeira classe");

        jLabel11.setText("Classe economica");

        jLabel12.setText("Classe executiva");

        jLabel13.setText("Tarifas:");

        vEdit.setText("Editar");
        vEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vEditActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.setEnabled(false);

        jTextField3.setText("jTextField3");
        jTextField3.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domingo", "Segunda", "Terca", "Quarta", "Quinta", "Sexta", "Sabado" }));
        jComboBox1.setEnabled(false);

        jTextField2.setText("jTextField2");
        jTextField2.setEnabled(false);

        jTextField4.setText("jTextField4");
        jTextField4.setEnabled(false);

        jTextField5.setText("jTextField5");
        jTextField5.setEnabled(false);

        vInserir.setText("Inserir");
        vInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vInserirActionPerformed(evt);
            }
        });

        vCancelar.setText("Cancelar");
        vCancelar.setEnabled(false);
        vCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Numero");

        jLabel8.setText("Aeroporto de partida");

        jLabel9.setText("Hora de partida");

        jLabel14.setText("Hora de chegada");

        jLabel15.setText("Aeroporto de chegada");

        jComboBox2.setEnabled(false);

        jComboBox3.setEnabled(false);

        jTextField6.setText("jTextField6");
        jTextField6.setEnabled(false);

        jTextField7.setText("jTextField6");
        jTextField7.setEnabled(false);

        jLabel20.setText("Mostrando trecho");

        jLabel21.setText("i");

        jLabel22.setText("de");

        jLabel23.setText("N");

        tPrimeiro.setText("Primeiro trecho");
        tPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrimeiroActionPerformed(evt);
            }
        });

        tAnt.setText("Trecho Anterior");
        tAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAntActionPerformed(evt);
            }
        });

        tProx.setText("Próximo trecho");
        tProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tProxActionPerformed(evt);
            }
        });

        tUlt.setText("Ultimo trecho");
        tUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUltActionPerformed(evt);
            }
        });

        tEdit.setText("Editar");
        tEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEditActionPerformed(evt);
            }
        });

        tInserir.setText("Inserir");
        tInserir.setEnabled(false);
        tInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tInserirActionPerformed(evt);
            }
        });

        tCancelar.setText("Cancelar");
        tCancelar.setEnabled(false);
        tCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCancelarActionPerformed(evt);
            }
        });

        jTextField8.setText("jTextField8");
        jTextField8.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tProx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tUlt)
                        .addGap(6, 6, 6)
                        .addComponent(tEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tInserir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, 0, 283, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, 283, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTextField7))))
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23))
                    .addComponent(tCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tProx)
                    .addComponent(tPrimeiro)
                    .addComponent(tUlt)
                    .addComponent(tAnt)
                    .addComponent(tEdit)
                    .addComponent(tInserir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("Atenção: a edição não está funcionando!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, 217, Short.MAX_VALUE))))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField4)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(673, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vPrim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vAnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vProx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vUlt)
                                .addGap(6, 6, 6)
                                .addComponent(vEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vInserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                                .addComponent(jLabel24)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vProx)
                                    .addComponent(vPrim)
                                    .addComponent(vUlt)
                                    .addComponent(vAnt)
                                    .addComponent(vEdit)
                                    .addComponent(vInserir)
                                    .addComponent(vCancelar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fechar)
                                    .addComponent(jLabel24))
                                .addGap(4, 4, 4)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void vProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vProxActionPerformed
        if(index < voos.size() - 1){
            this.index++;
            this.mostraVoo();
        }
    }//GEN-LAST:event_vProxActionPerformed

    private void vPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPrimActionPerformed
        this.index = 0;
        this.mostraVoo();
    }//GEN-LAST:event_vPrimActionPerformed

    private void vUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vUltActionPerformed
        this.index = this.voos.size() - 1;
        this.mostraVoo();
    }//GEN-LAST:event_vUltActionPerformed

    private void vAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vAntActionPerformed
        if(this.index >= 1){
            this.index--;
            this.mostraVoo();
        }
    }//GEN-LAST:event_vAntActionPerformed

    private void vEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vEditActionPerformed
        alteraEstados();
        if (vEdit.getText().equals("Salvar")){
            vEdit.setText("Editar");
            vInserir.setEnabled(true);
        }else{
            vEdit.setText("Salvar");
            vInserir.setEnabled(false);
        }
    }//GEN-LAST:event_vEditActionPerformed

    private void vInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vInserirActionPerformed
        alteraEstados();
        if (vInserir.getText().equals("Salvar")){
            vInserir.setText("Inserir");
            vEdit.setEnabled(true);
            insereVoo();
        }else{
            vInserir.setText("Salvar");
            vEdit.setEnabled(false);
            novoVoo();
        }
    }//GEN-LAST:event_vInserirActionPerformed

    private void vCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCancelarActionPerformed
        // Editar
        if(vEdit.getText().equals("Salvar")){
            estado = false;
            alteraEstados();
            vEdit.setText("Editar");
            vInserir.setEnabled(true);
            JToggleButton.ToggleButtonModel model = new JToggleButton.ToggleButtonModel();
            model.setRollover(true);
            vEdit.setModel(model);
        }
        // Inserir
        else if(vInserir.getText().equals("Salvar")){
            estado = false;
            alteraEstados();
            vInserir.setText("Inserir");
            vEdit.setEnabled(true);
            JToggleButton.ToggleButtonModel model = new JToggleButton.ToggleButtonModel();
            model.setRollover(true);
            vInserir.setModel(model);
            jLabel19.setText(Integer.toString(Integer.parseInt(jLabel19.getText()) - 1));
            atualizaVoos();
        }
    }//GEN-LAST:event_vCancelarActionPerformed

    private void tPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrimeiroActionPerformed
        this.index_trecho = 0;
        this.mostraTrecho();
    }//GEN-LAST:event_tPrimeiroActionPerformed

    private void tAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAntActionPerformed
        if(this.index_trecho >= 1){
            this.index_trecho--;
            this.mostraTrecho();
        }
    }//GEN-LAST:event_tAntActionPerformed

    private void tProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tProxActionPerformed
         if(index_trecho < voos.get(index).getTrechos().size() - 1){
            this.index_trecho++;
            this.mostraTrecho();
        }
    }//GEN-LAST:event_tProxActionPerformed

    private void tUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUltActionPerformed
        this.index_trecho = this.voos.get(index).getTrechos().size() - 1;
        this.mostraTrecho();
    }//GEN-LAST:event_tUltActionPerformed

    private void tEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEditActionPerformed
        alteraEstadosTrechos();
        if (tEdit.getText().equals("Salvar")){
            tEdit.setText("Editar");
            tInserir.setEnabled(true);
        }else{
            tEdit.setText("Salvar");
            tInserir.setEnabled(false);
        }
    }//GEN-LAST:event_tEditActionPerformed

    private void tInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tInserirActionPerformed
        alteraEstadosTrechos();
        if (tInserir.getText().equals("Salvar")){
            tInserir.setText("Inserir");
            tEdit.setEnabled(true);
            insereTrecho();
        }else{
            tInserir.setText("Salvar");
            tEdit.setEnabled(false);
            novoTrecho();
        }
    }//GEN-LAST:event_tInserirActionPerformed

    private void tCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCancelarActionPerformed
        // Editar
        if(tEdit.getText().equals("Salvar")){
            estado_trecho = false;
            alteraEstadosTrechos();
            tEdit.setText("Editar");
            tInserir.setEnabled(true);
            JToggleButton.ToggleButtonModel model = new JToggleButton.ToggleButtonModel();
            model.setRollover(true);
            tEdit.setModel(model);
        }
        // Inserir
        else if(tInserir.getText().equals("Salvar")){
            estado_trecho = false;
            alteraEstadosTrechos();
            tInserir.setText("Inserir");
            tEdit.setEnabled(true);
            JToggleButton.ToggleButtonModel model = new JToggleButton.ToggleButtonModel();
            model.setRollover(true);
            tInserir.setModel(model);
            jLabel23.setText(Integer.toString(Integer.parseInt(jLabel23.getText()) - 1));
            this.trechos_tmp.removeAllElements();
        }
    }//GEN-LAST:event_tCancelarActionPerformed

    private void novoVoo(){
        novoTrecho();
        limpaCampos();
        jLabel19.setText(Integer.toString(Integer.parseInt(jLabel19.getText()) + 1));
    }

    private void insereTrecho(){
        Trecho trecho_tmp = new Trecho();
        trecho_tmp.setNumero(Integer.parseInt(jTextField8.getText()));
        trecho_tmp.setAeroporto_chegada(aeroportos.get(jComboBox2.getSelectedIndex()-1));
        trecho_tmp.setAeroporto_partida(aeroportos.get(jComboBox3.getSelectedIndex()-1));
        trecho_tmp.setHora_chegada(jTextField7.getText());
        trecho_tmp.setHora_partida(jTextField6.getText());
        trechos_tmp.add(trecho_tmp);
    }

    private void novoTrecho(){
        limpaCamposTrecho();
        jLabel23.setText(Integer.toString(Integer.parseInt(jLabel23.getText()) + 1));
    }

    private void insereVoo(){
        Voo voo = new Voo(Integer.parseInt(jTextField1.getText()), jComboBox1.getSelectedItem().toString(), jTextField3.getText());
        Tarifas tarifas = new Tarifas();
        double economica = 0;
        double executiva = 0;
        double primeira_classe = 0;
        if (!jTextField2.getText().isEmpty())
            tarifas.setValor("ECONOMICA", Double.parseDouble(jTextField2.getText()));
        else
            tarifas.setValor("ECONOMICA", economica);
        if (!jTextField4.getText().isEmpty())
            tarifas.setValor("EXECUTIVA", Double.parseDouble(jTextField4.getText()));
        else
            tarifas.setValor("EXECUTIVA", executiva);
        if (!jTextField5.getText().isEmpty())
            tarifas.setValor("PRIMEIRA CLASSE", Double.parseDouble(jTextField5.getText()));
        else
            tarifas.setValor("PRIMEIRA CLASSE", primeira_classe);
        voo.setTarifas(tarifas);
        /*Vector<Trecho> t_tmp = new Vector<Trecho>();
        for (int i = 0; i < trechos_tmp.size(); i++){
            t_tmp.add(trechos_tmp.get(i).getInstance());
        }*/
        voo.setTrechos(trechos_tmp);
        ControllerVoo cv = new ControllerVoo();
        try{
            cv.insereVoo(voo);
        }catch (SQLException e){
            e.printStackTrace();
        }
        try{
            for (int i = 0; i < trechos_tmp.size(); i++){
                JOptionPane.showMessageDialog(null, "Inserindo trecho " + trechos_tmp.get(i).getNumero());
                cv.insereTrecho(voo.getNumero(), trechos_tmp.get(i));
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        atualizaVoos();
    }

    private void limpaCamposTrecho(){
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jComboBox2.setSelectedItem("");
        jComboBox3.setSelectedItem("");
        jLabel21.setText("0");
        jLabel23.setText("-1");
    }

    private void limpaCampos(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(0);
    }

    private void alteraEstadosTrechos(){
        if (estado_trecho){
            estado_trecho = false;
        }else{
            estado_trecho = true;
        }
        jTextField6.setEnabled(!estado_trecho);
        jTextField7.setEnabled(!estado_trecho);
        jTextField8.setEnabled(!estado_trecho);
        tCancelar.setEnabled(!estado_trecho);
        jComboBox2.setEnabled(!estado_trecho);
        jComboBox3.setEnabled(!estado_trecho);
        fechar.setEnabled(estado_trecho);
        tPrimeiro.setEnabled(estado_trecho);
        tProx.setEnabled(estado_trecho);
        tUlt.setEnabled(estado_trecho);
        tAnt.setEnabled(estado_trecho);
    }

    private void alteraEstados(){
        if (estado){
            estado = false;
        }else{
            estado = true;
        }
        jTextField1.setEnabled(!estado);
        jTextField2.setEnabled(!estado);
        jTextField3.setEnabled(!estado);
        jTextField4.setEnabled(!estado);
        jTextField5.setEnabled(!estado);
        tEdit.setEnabled(!estado);
        tInserir.setEnabled(!estado);
        vCancelar.setEnabled(!estado);
        jComboBox1.setEnabled(!estado);
        fechar.setEnabled(estado);
        vPrim.setEnabled(estado);
        vProx.setEnabled(estado);
        vUlt.setEnabled(estado);
        vAnt.setEnabled(estado);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VooFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fechar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton tAnt;
    private javax.swing.JButton tCancelar;
    private javax.swing.JToggleButton tEdit;
    private javax.swing.JToggleButton tInserir;
    private javax.swing.JButton tPrimeiro;
    private javax.swing.JButton tProx;
    private javax.swing.JButton tUlt;
    private javax.swing.JButton vAnt;
    private javax.swing.JButton vCancelar;
    private javax.swing.JToggleButton vEdit;
    private javax.swing.JToggleButton vInserir;
    private javax.swing.JButton vPrim;
    private javax.swing.JButton vProx;
    private javax.swing.JButton vUlt;
    // End of variables declaration//GEN-END:variables

    private void atualizaAeroportos(){
        jComboBox3.addItem("");
        jComboBox2.addItem("");
        try{
            aeroportos = ControllerAeroporto.fetchAeroporotos();
            for (int i = 0; i < aeroportos.size(); i++)
                jComboBox2.addItem(aeroportos.get(i).getNome());
            for (int i = 0; i < aeroportos.size(); i++)
                jComboBox3.addItem(aeroportos.get(i).getNome());
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    private void atualizaVoos(){
        try{
            this.voos = ControllerVoo.fetchVoos();
            this.atualizaAeroportos();
            this.mostraVoo();
        }catch(SQLException sqle){
            JOptionPane.showMessageDialog(null, "Erro sql: " + "\n" + sqle.getMessage(),"Erro",JOptionPane.INFORMATION_MESSAGE);
        }catch (ArrayIndexOutOfBoundsException e){
            // vetor vazio: nao faz nada
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro " + e.getMessage(),"Erro",JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void mostraVoo(){
        this.jTextField1.setText(Integer.toString(voos.get(index).getNumero()));
        this.jComboBox1.setSelectedIndex(voos.get(index).getNDiaSemana());
        this.jTextField3.setText(voos.get(index).getCompanhiaAerea());
        this.jTextField2.setText(Double.toString(voos.get(index).getTarifa("ECONOMICA")));
        this.jTextField4.setText(Double.toString(voos.get(index).getTarifa("EXECUTIVA")));
        this.jTextField5.setText(Double.toString(voos.get(index).getTarifa("PRIMEIRA CLASSE")));
        this.jLabel17.setText(Integer.toString(this.index + 1));
        this.jLabel19.setText(Integer.toString(voos.size()));
        mostraTrecho();
    }


        private void mostraTrecho(){
            Vector<Trecho> trecho_tmp = voos.get(index).getTrechos();
            if (trecho_tmp.size() > 0){
                jTextField8.setText(Integer.toString(trecho_tmp.get(index_trecho).getNumero()));
                jComboBox2.setSelectedItem(trecho_tmp.get(index_trecho).getAeroporto_partida().getNome());
                jTextField6.setText(trecho_tmp.get(index_trecho).getHora_partida());
                jComboBox3.setSelectedItem(trecho_tmp.get(index_trecho).getAeroporto_chegada().getNome());
                jTextField7.setText(trecho_tmp.get(index_trecho).getHora_chegada());
                this.jLabel21.setText(Integer.toString(this.index_trecho + 1));
                this.jLabel23.setText(Integer.toString(trecho_tmp.size()));
            }else{
                jTextField8.setText("");
                jComboBox2.setSelectedItem("");
                jTextField6.setText("");
                jComboBox3.setSelectedItem("");
                jTextField7.setText("");
                this.jLabel21.setText("0");
                this.jLabel23.setText("0");
        }
    }
}
